// ── Reading levels, quotes, curated passages, and their quizzes ──────────────

export const LEVELS = [
  { n:1,  min:100, max:149, comp:60, title:"Novice"       },
  { n:2,  min:150, max:199, comp:62, title:"Beginner"     },
  { n:3,  min:200, max:239, comp:65, title:"Developing"   },
  { n:4,  min:240, max:279, comp:68, title:"Intermediate" },
  { n:5,  min:280, max:319, comp:72, title:"Proficient"   },
  { n:6,  min:320, max:369, comp:75, title:"Advanced"     },
  { n:7,  min:370, max:429, comp:78, title:"Expert"       },
  { n:8,  min:430, max:499, comp:80, title:"Master"       },
  { n:9,  min:500, max:599, comp:83, title:"Elite"        },
  { n:10, min:600, max:900, comp:85, title:"Legendary"    },
];

export const QUOTES = [
  { q:"A reader lives a thousand lives before he dies.",           a:"George R.R. Martin" },
  { q:"Reading is to the mind what exercise is to the body.",      a:"Joseph Addison"     },
  { q:"Not all readers are leaders, but all leaders are readers.", a:"Harry S. Truman"    },
  { q:"Once you learn to read, you will be forever free.",         a:"Frederick Douglass" },
  { q:"A book is a dream that you hold in your hands.",            a:"Neil Gaiman"        },
  { q:"There is no friend as loyal as a book.",                    a:"Ernest Hemingway"   },
];

export const PASSAGES = [
  {
    id:"p1", title:"The Quantum Leap", genre:"Science Fiction", level:5, wordCount:312,
    text:`The laboratory hummed with an almost imperceptible frequency that Dr. Elena Vasquez had learned to associate with breakthrough moments. Three years of incremental progress had culminated in tonight's experiment, and as she adjusted the quantum field stabilizer, she allowed herself a rare moment of anticipation.\n\nThe particle array stretched across the chamber like a constellation of frozen stars. Each node represented thousands of calculations, millions of variables collapsed into a single elegant equation that her mentor, the formidable Professor Chen, had once declared theoretically impossible.\n\n"Theoretical impossibility," she murmured to herself, "is merely an invitation."\n\nThe readout flickered. For exactly 0.003 seconds, the entanglement held — two particles maintaining perfect correlation across a distance that should have severed any meaningful connection. Elena's breath caught in her throat. The implications cascaded through her mind with terrifying velocity: instantaneous communication, unhackable encryption, the dissolution of every barrier that distance had ever imposed upon human connection.\n\nThen the array collapsed. The hum dissipated. The laboratory returned to its ordinary silence.\n\nBut Elena was already drafting the paper in her head, her fingers moving across the keyboard with the particular urgency of someone who has just glimpsed the future and cannot bear the thought of losing it again. Tomorrow, the world would still look the same. But she knew, with the absolute certainty of empirical evidence, that nothing would ever be quite the same again.\n\nShe saved the data seventeen times in succession, each backup a prayer to the gods of irreversibility.`,
    tags:["science fiction","technology"],
  },
  {
    id:"p2", title:"Cognitive Load Theory", genre:"Academic", level:7, wordCount:287,
    text:`Cognitive load theory, developed by educational psychologist John Sweller in the 1980s, posits that the human working memory has a finite capacity and that instructional design must account for this limitation to optimize learning outcomes. The theory distinguishes among three types of cognitive load: intrinsic, extraneous, and germane.\n\nIntrinsic load refers to the inherent complexity of the material being learned — a function of element interactivity, or the degree to which individual components must be processed simultaneously to be understood. High-element-interactivity material, such as grammatical syntax or algebraic manipulation, imposes substantial intrinsic load because learners cannot process each element in isolation.\n\nExtraneous load, by contrast, arises from suboptimal instructional design — redundant information, poorly organized presentations, or formats that require learners to split their attention between multiple sources. Unlike intrinsic load, extraneous load is theoretically eliminable through careful pedagogical intervention.\n\nGermane load describes the cognitive resources devoted to schema formation and automation — the processes by which novel information is integrated into long-term memory structures. Contemporary revisions of the theory have reconceptualized germane load not as a separate category but as the productive application of working memory resources toward schema acquisition.\n\nPractical implications for educators are considerable: worked examples reduce extraneous load during initial skill acquisition; problem completion tasks scaffold the transition to independent problem solving; and variability in practice conditions enhances schema generalization. The theory remains one of the most empirically supported frameworks in instructional psychology.`,
    tags:["psychology","education"],
  },
  {
    id:"p3", title:"Rain-Drenched Encounter", genre:"Literary Fiction", level:8, wordCount:298,
    text:`The deluge arrived without preamble, as though the sky had been holding its breath for precisely this moment. Mira ducked beneath the inadequate awning of a shuttered parfumerie, her coat already saturated, her composure performing the kind of studied nonchalance that only the truly soaked can muster.\n\nIt was in this state of aqueous ignominy that she noticed him — a man of perhaps forty, possessing the kind of face that suggested a turbulent biography, standing at the periphery of the canopy's protection as though he had not yet decided whether shelter was something he deserved.\n\n"You may stand closer," she said. "The awning's jurisdiction extends at least another meter."\n\nHe regarded her with an expression of calibrated surprise, the kind assembled by someone who encounters unexpected kindness so rarely that they have developed a separate cognitive apparatus for processing it.\n\n"Mira Delacroix," she offered, extending a hand that was essentially indistinguishable from the rain.\n\n"Thomas Vane." His handshake was firm, deliberate — a handshake that communicated a history of being underestimated. "I was beginning to suspect this street was entirely hostile to human occupation."\n\n"Most streets are, in weather like this. They revert to their fundamental nature — indifferent, ancient, completely unimpressed by our architectural pretensions."\n\nHe laughed, a genuinely unguarded sound that seemed to surprise him more than it surprised her. And in that moment, with water running in rivulets along the cobblestones and the city reduced to a moody impressionistic blur, Mira had the particular sensation of encountering something consequential disguised as coincidence.`,
    tags:["fiction","literary"],
  },
  {
    id:"p4", title:"The Architecture of Memory", genre:"Academic", level:6, wordCount:264,
    text:`Memory is not a filing cabinet. This metaphor, intuitive as it seems, fundamentally misrepresents how human recollection actually functions. Rather than retrieving a stored file, remembering is an act of reconstruction — an elaborate synthesis of fragments, schema, and contextual cues that produces something resembling the original experience, but never exactly replicates it.\n\nNeuroscientific research has illuminated the distributed nature of memory storage. Episodic memories — those tied to specific personal experiences — engage a network of brain regions including the hippocampus, prefrontal cortex, and amygdala. The hippocampus plays a particularly critical role in encoding and consolidating new memories, a function devastatingly illustrated by patients with hippocampal damage who cannot form new long-term memories while retaining older ones.\n\nSemantic memory, by contrast, stores factual knowledge abstracted from specific experiences. A person who knows that Paris is the capital of France does not necessarily remember learning this fact; the information has been decontextualized and integrated into a broader conceptual network.\n\nThe reconstructive nature of memory has profound implications for reliability. Each act of retrieval slightly modifies the stored trace — a phenomenon known as reconsolidation — making memory susceptible to distortion through suggestion, context, and the passage of time. Eyewitness testimony, long considered legally compelling, has been substantially undermined by decades of research demonstrating the malleability of human recollection.`,
    tags:["neuroscience","psychology","memory"],
  },
  {
    id:"p5", title:"The Last Lighthouse Keeper", genre:"Fiction", level:4, wordCount:243,
    text:`The light swept the darkness in its slow, patient arc, as it had every night for forty-three years. Martin stood at the window of the lamp room and watched the beam cross the black water, the same motion he had watched ten thousand times before, and still he found it calming.\n\nThe automated systems would take over in the spring. The maritime authority had sent the letter in October, formal and apologetic in equal measure, noting that manned lighthouses were increasingly impractical in an era of GPS navigation and satellite communication. Martin had read it three times, folded it carefully, and placed it in the drawer beneath the logbooks that stretched back to 1947.\n\nHis predecessor, a man named Halvorsen who had retired with remarkable reluctance in 1981, had told him something on his first day that Martin had carried ever since: "The light isn't for the ships," the old man had said. "The ships have radar now. The light is for the sea. To remind it that we're still watching."\n\nMartin had thought this sentimental at the time. He no longer did.\n\nBelow, the Atlantic moved in its restless, incomprehensible way, indifferent to his vigil. But he would watch it anyway, for as many nights as remained to him. Some duties, he had come to understand, derived their meaning entirely from the act of performing them.`,
    tags:["fiction","atmosphere","literary"],
  },
  {
    id:"p6", title:"Emergence and Complexity", genre:"Academic", level:9, wordCount:301,
    text:`Emergence — the phenomenon whereby complex systems exhibit properties irreducible to, and unpredictable from, the properties of their constituent components — represents one of the most philosophically challenging concepts in contemporary science. When individual neurons fire, we get cognition. When water molecules interact, we get wetness. When simple trading rules aggregate, we get market bubbles. The emergent property belongs to the system as a whole and cannot be located in any single part.\n\nThe distinction between weak and strong emergence has occupied philosophers of science for decades. Weak emergence describes properties that are, in principle, derivable from lower-level descriptions through sufficient computational power — even if such derivation would be practically intractable. Strong emergence, more controversially, posits properties that are fundamentally irreducible: no amount of knowledge about components would allow prediction of the emergent behavior.\n\nConsciousness is the most contested candidate for strong emergence. The hard problem of consciousness — why physical processes give rise to subjective experience at all — remains stubbornly resistant to reductionist explanation. Attempts to locate qualia in neural architecture confront the explanatory gap between third-person physical description and first-person phenomenal experience.\n\nComplex adaptive systems theory offers a different framework: emergence is not merely an epistemological limitation but an ontological feature of reality. Systems with nonlinear dynamics, feedback loops, and sensitive dependence on initial conditions generate novelty that cannot be anticipated from initial conditions alone. In this view, the universe is fundamentally creative — perpetually generating forms of organization that transcend their origins.`,
    tags:["philosophy","science","complexity"],
  },
  {
    id:"p7", title:"The First Morning in Lagos", genre:"Fiction", level:3, wordCount:238,
    text:`Tunde woke before the generator came on. In those few quiet minutes, the city breathed differently — slower, softer, as if Lagos itself needed a moment before resuming its relentless performance.\n\nHe lay still on the narrow bed and listened. A rooster somewhere behind the compound. The distant call to prayer drifting from the mosque on Adeleke Street. The sound of his mother already moving in the kitchen, the rhythmic thump of a pestle that had been waking him every morning for twenty-two years.\n\nHe was leaving today.\n\nThe scholarship letter was folded in the inside pocket of his good jacket, which hung on the door like a question mark. Edinburgh. The word had felt impossible in his mouth when he first read it, a sound from a different kind of life. Now it felt simply heavy.\n\nHis mother appeared in the doorway. She did not say anything for a long moment, just looked at him the way she sometimes looked at the photographs on the wall — with a careful attention, as if trying to memorize something she suspected she might not always have.\n\n"Eat first," she said finally. "Everything else can wait until you have eaten."\n\nHe got up. Outside, the generator coughed to life, and Lagos resumed its noise, and his last ordinary morning began.`,
    tags:["fiction","africa","coming of age"],
  },
  {
    id:"p8", title:"How Habits Form", genre:"Academic", level:4, wordCount:251,
    text:`Every habit, no matter how complex it appears, follows the same basic structure: a cue, a routine, and a reward. This three-part loop, identified by researchers at MIT in the 1990s through experiments with rats navigating mazes, underlies virtually every habitual behavior in humans — from brushing teeth to checking a phone to reaching for a cigarette.\n\nThe cue is a trigger that tells the brain to enter automatic mode and which habit to use. It can be a time of day, an emotional state, a location, the presence of certain people, or an immediately preceding action. The routine is the physical, mental, or emotional behavior that follows the cue. The reward is what tells the brain whether the loop is worth remembering for the future.\n\nOver time, as a cue-routine-reward pattern is repeated, the brain begins to anticipate the reward the moment the cue appears. This anticipation — called craving — is what gives habits their power and their persistence. It is also what makes habits so difficult to break: removing the routine does not remove the craving, which continues to be triggered by the original cue.\n\nThe most reliable method for changing a habit is not elimination but substitution: keeping the existing cue and reward while inserting a new routine in between. This approach works because the neural pathway created by the original habit remains intact; only its behavioral expression is altered. Understanding this mechanism is the first step toward exercising deliberate control over the patterns that quietly govern daily life.`,
    tags:["psychology","habits","self-improvement"],
  },
  {
    id:"p9", title:"The Cartographer's Dilemma", genre:"Science Fiction", level:6, wordCount:274,
    text:`Every map is a lie. This was the first thing Professor Osei told his students, and the last thing they believed.\n\nMaps impose stillness on things that move. They draw lines where lines do not exist. They reduce the infinite texture of the world to a surface you can fold and put in your pocket. Every map is an argument about what matters — and therefore, silently, about what does not.\n\nDr. Amara Osei had spent thirty years making maps of places that did not officially exist: disputed borders, contested coastlines, territories whose names changed depending on who you asked. Her work had been cited in international court cases. It had also, twice, gotten her detained at airports.\n\nNow she stood at the edge of something unprecedented. The survey drones had returned from the deep Saharan coordinates with data that refused to make sense. The topography was wrong — not incorrect in the way data was sometimes corrupted, but wrong in the way a dream is wrong, internally consistent yet fundamentally impossible.\n\nA valley that appeared in evening scans was absent by morning. A ridge that the lidar confirmed at thirty meters simply was not there when the ground team arrived.\n\n"The land is moving," said her assistant, Kofi, not helpfully.\n\n"Land doesn't move on that timescale," Amara said.\n\n"Then perhaps," Kofi said carefully, "we need a different kind of map."\n\nShe looked at the data again. He was right, she realized — but she had no idea what kind of map could hold a place like this.`,
    tags:["science fiction","africa","mystery"],
  },
  {
    id:"p10", title:"The Economics of Sleep", genre:"Academic", level:5, wordCount:262,
    text:`Sleep deprivation costs the United States an estimated 411 billion dollars annually in lost productivity — a figure that places insufficient sleep among the most expensive public health problems in the developed world. Yet despite overwhelming evidence of its physiological necessity, sleep remains culturally undervalued, frequently sacrificed in the pursuit of professional achievement.\n\nThe consequences of this trade-off are considerably more severe than most people appreciate. After seventeen hours without sleep, cognitive performance declines to a level equivalent to a blood alcohol concentration of 0.05 percent. After twenty-four hours, that equivalence rises to 0.10 percent — legally intoxicated in every jurisdiction. Unlike alcohol impairment, however, sleep deprivation impairs one's ability to accurately assess one's own level of impairment, creating a dangerous confidence in compromised performance.\n\nThe mechanisms behind these effects are well understood. During sleep, the glymphatic system — a network of channels surrounding the brain's blood vessels — clears metabolic waste products that accumulate during waking hours, including amyloid-beta proteins associated with Alzheimer's disease. The hippocampus consolidates short-term memories into long-term storage. Stress hormones are regulated. Immune function is restored.\n\nPerhaps most significantly for knowledge workers, the prefrontal cortex — the region responsible for judgment, creativity, and nuanced decision-making — is disproportionately sensitive to sleep loss. The very cognitive functions that professionals most rely upon are the first to deteriorate.\n\nIn this light, the cultural equation of sleeplessness with productivity is not merely misguided. It is measurably self-defeating.`,
    tags:["health","science","productivity"],
  },
  {
    id:"p11", title:"Letters Never Sent", genre:"Literary Fiction", level:7, wordCount:256,
    text:`My grandmother kept them in a shoebox under the bed she had slept in for fifty-one years. After she died, my mother found them before I did, and when she handed them to me her face had the particular expression of someone delivering news they have not yet fully absorbed themselves.\n\nThere were forty-three letters. All addressed to a man named Romuald Szymanski at an address in Warsaw that no longer existed. None of them had ever been posted.\n\nThe earliest was dated August 1959. The most recent, December 2019 — three months before she died, in her ninety-first year, in the same room where she had written all the others.\n\nI do not read Polish with any fluency. My grandmother had always spoken to me in English, a language she had mastered with characteristic determination after arriving in London in 1946 with nothing except a cardboard suitcase and the kind of composure that can only be assembled from the ruins of something unimaginable.\n\nI had the letters translated by a professor at University College. She called me after the third one to ask if I was all right.\n\nWhat I learned was this: my grandmother had been twenty-one years old when she last saw Romuald Szymanski. She had spent the following seventy years conducting, in private, the conversation that history had interrupted. The letters were not expressions of grief. They were simply — and this is what undid me — a continuation. As if she had simply refused to accept that the story was over.`,
    tags:["literary fiction","history","family"],
  },
  {
    id:"p12", title:"The Deep Ocean", genre:"Academic", level:8, wordCount:289,
    text:`More than eighty percent of the ocean remains unmapped, unobserved, and unexplored — a fact that becomes increasingly extraordinary when one considers that the ocean constitutes roughly ninety-seven percent of Earth's habitable volume. We have more detailed maps of the lunar surface than we do of the seafloor.\n\nThe practical obstacles to deep-sea exploration are formidable. At a depth of one thousand meters, pressure reaches approximately one hundred atmospheres — sufficient to crush most conventional equipment. At the deepest point in the ocean, the Challenger Deep in the Mariana Trench, pressure exceeds one thousand atmospheres. Only three descents by humans have ever reached that depth, the most recent in 2019.\n\nYet the organisms that inhabit these crushing depths have evolved solutions of considerable elegance. The barreleye fish maintains transparent fluid-filled chambers in its head that allow it to rotate its eyes upward to detect the silhouettes of prey against faint surface light. The anglerfish generates bioluminescent lures through a symbiotic relationship with bacteria that produce light via chemical oxidation. The Pompeii worm tolerates temperatures exceeding eighty degrees Celsius at hydrothermal vents while its anterior end remains in water near two degrees — the steepest temperature gradient endured by any known animal.\n\nWhat these adaptations suggest, to biologists of a certain disposition, is less a catalogue of curiosities than a reminder: life does not merely tolerate extreme conditions. It specializes in them. Every environment that has ever seemed too hostile for biology has eventually yielded organisms that found it, specifically, home.`,
    tags:["science","ocean","biology"],
  },
];

export const QUIZZES = {
  p1: [
    { id:"q1", type:"mc", q:"What did the entanglement achieve for exactly 0.003 seconds?", choices:["Nuclear fusion","Perfect particle correlation","Time reversal","Quantum tunneling"], correct:1, exp:"Two particles maintained perfect correlation across a distance that should have severed any connection." },
    { id:"q2", type:"tf", q:"Professor Chen believed Elena's equation was theoretically achievable.", choices:["True","False"], correct:1, exp:"Professor Chen declared it 'theoretically impossible' — Elena treated this as an invitation." },
    { id:"q3", type:"mc", q:"What was Elena's immediate reaction after the experiment ended?", choices:["She called Professor Chen","She began drafting a paper","She ran the experiment again","She celebrated with colleagues"], correct:1, exp:"Elena immediately started drafting the paper in her head while typing urgently." },
    { id:"q4", type:"mc", q:"How many times did Elena save her data?", choices:["3","7","17","Once"], correct:2, exp:"She saved the data seventeen times in succession." },
    { id:"q5", type:"tf", q:"The particle array was still functional at the end of the passage.", choices:["True","False"], correct:1, exp:"The array collapsed and the hum dissipated, returning the laboratory to silence." },
  ],
  p2: [
    { id:"q1", type:"mc", q:"Who developed Cognitive Load Theory?", choices:["Vygotsky","Piaget","John Sweller","Benjamin Bloom"], correct:2, exp:"John Sweller developed the theory in the 1980s." },
    { id:"q2", type:"mc", q:"Which load type is caused by poor instructional design?", choices:["Intrinsic","Extraneous","Germane","Schema"], correct:1, exp:"Extraneous load arises from suboptimal instructional design." },
    { id:"q3", type:"tf", q:"Intrinsic load can be eliminated through better instructional design.", choices:["True","False"], correct:1, exp:"Only extraneous load is eliminable; intrinsic load is inherent to material complexity." },
    { id:"q4", type:"mc", q:"What does germane load relate to?", choices:["Material difficulty","Poor presentation","Schema formation and automation","Working memory limits"], correct:2, exp:"Germane load describes resources devoted to schema formation." },
  ],
  p3: [
    { id:"q1", type:"mc", q:"Where did Mira take shelter from the rain?", choices:["A café","A shuttered parfumerie","A hotel lobby","A bookshop"], correct:1, exp:"Mira ducked beneath the awning of a shuttered parfumerie." },
    { id:"q2", type:"tf", q:"Thomas Vane was accustomed to receiving unexpected kindness.", choices:["True","False"], correct:1, exp:"He had a 'separate cognitive apparatus for processing' unexpected kindness — implying it was rare." },
    { id:"q3", type:"mc", q:"What did Mira sense at the passage's end?", choices:["Annoyance at the stranger","Something consequential disguised as coincidence","A desire to leave quickly","Recognition of Thomas from before"], correct:1, exp:"Mira had 'the particular sensation of encountering something consequential disguised as coincidence.'" },
  ],
  p4: [
    { id:"q1", type:"mc", q:"According to the passage, memory is best described as:", choices:["A filing cabinet","A database","An act of reconstruction","A photograph"], correct:2, exp:"The passage argues memory is 'an act of reconstruction.'" },
    { id:"q2", type:"mc", q:"Which brain region plays a critical role in encoding new memories?", choices:["Cerebellum","Hippocampus","Occipital lobe","Cerebral cortex"], correct:1, exp:"The hippocampus plays a particularly critical role in encoding and consolidating new memories." },
    { id:"q3", type:"tf", q:"Semantic memory retains the specific context in which facts were learned.", choices:["True","False"], correct:1, exp:"Semantic memory stores factual knowledge 'abstracted from specific experiences.'" },
  ],
  p5: [
    { id:"q1", type:"mc", q:"How long had Martin worked at the lighthouse?", choices:["Twenty years","Thirty years","Forty-three years","Fifty years"], correct:2, exp:"Martin had watched the beam sweep the darkness 'every night for forty-three years.'" },
    { id:"q2", type:"mc", q:"What was Halvorsen's insight about the lighthouse beam?", choices:["It warns ships of rocks","It is for the sea, not the ships","It powers the radio beacon","It scares away birds"], correct:1, exp:"Halvorsen said the light is for the sea — to remind it that we're still watching." },
    { id:"q3", type:"tf", q:"Martin immediately found Halvorsen's philosophy sentimental and wise.", choices:["True","False"], correct:1, exp:"Martin 'had thought this sentimental at the time' — he only came to understand it later." },
  ],
  p6: [
    { id:"q1", type:"mc", q:"What does 'emergence' refer to?", choices:["Simple behaviors in isolated systems","Properties irreducible to component parts","Predictable outcomes from basic rules","Gradual evolutionary changes"], correct:1, exp:"Emergence is when complex systems exhibit properties irreducible to their components." },
    { id:"q2", type:"mc", q:"What is the 'hard problem of consciousness'?", choices:["Understanding neural pathways","Why we forget dreams","Why physical processes give rise to subjective experience","How memories are stored"], correct:2, exp:"The hard problem asks why physical processes give rise to subjective experience." },
    { id:"q3", type:"tf", q:"Strong emergence claims properties can always be derived with enough computation.", choices:["True","False"], correct:1, exp:"Weak emergence allows derivation in principle; strong emergence posits fundamentally irreducible properties." },
  ],
  p7: [
    { id:"q1", type:"mc", q:"Where is Tunde's scholarship taking him?", choices:["London","New York","Edinburgh","Accra"], correct:2, exp:"The scholarship letter said Edinburgh." },
    { id:"q2", type:"tf", q:"Tunde's mother was still asleep when he woke up.", choices:["True","False"], correct:1, exp:"His mother was already moving in the kitchen, using a pestle." },
    { id:"q3", type:"mc", q:"What hung on the door like a 'question mark'?", choices:["The scholarship letter","His good jacket","A calendar","A photograph"], correct:1, exp:"His good jacket hung on the door like a question mark." },
    { id:"q4", type:"tf", q:"Tunde felt purely excited about leaving.", choices:["True","False"], correct:1, exp:"The word Edinburgh 'felt simply heavy' — suggesting mixed or burdened feelings." },
  ],
  p8: [
    { id:"q1", type:"mc", q:"What are the three parts of the habit loop?", choices:["Trigger, action, outcome","Cue, routine, reward","Signal, behavior, result","Prompt, response, reinforcement"], correct:1, exp:"The habit loop consists of a cue, a routine, and a reward." },
    { id:"q2", type:"mc", q:"What is 'craving' in the context of habits?", choices:["The physical sensation of hunger","Anticipation of the reward triggered by the cue","Boredom that leads to habit formation","The guilt after breaking a habit"], correct:1, exp:"Craving is the brain's anticipation of the reward the moment the cue appears." },
    { id:"q3", type:"tf", q:"The best way to break a habit is to eliminate the cue entirely.", choices:["True","False"], correct:1, exp:"The most reliable method is substitution — keeping the cue and reward, replacing only the routine." },
    { id:"q4", type:"mc", q:"Where was the original habit loop research conducted?", choices:["Harvard","Stanford","MIT","Oxford"], correct:2, exp:"Researchers at MIT identified the loop through experiments with rats navigating mazes." },
  ],
  p9: [
    { id:"q1", type:"mc", q:"What is the first thing Professor Osei tells his students?", choices:["Every border is contested","Every map is a lie","Geography is political","Distance is relative"], correct:1, exp:"'Every map is a lie' is the first and last thing his students believe." },
    { id:"q2", type:"tf", q:"Amara's cartography work had caused her trouble at airports.", choices:["True","False"], correct:0, exp:"Her work had gotten her detained at airports twice." },
    { id:"q3", type:"mc", q:"What was strange about the valley in the drone data?", choices:["It was underwater","It appeared in evening scans but was absent by morning","It was twice the expected size","It moved northward overnight"], correct:1, exp:"The valley appeared in evening scans but was absent by morning." },
  ],
  p10: [
    { id:"q1", type:"mc", q:"After 17 hours without sleep, performance is equivalent to a BAC of:", choices:["0.02%","0.05%","0.08%","0.10%"], correct:1, exp:"After seventeen hours without sleep, cognitive performance equals a BAC of 0.05%." },
    { id:"q2", type:"mc", q:"What does the glymphatic system do during sleep?", choices:["Stores new memories","Regulates heart rate","Clears metabolic waste from the brain","Produces growth hormone"], correct:2, exp:"The glymphatic system clears metabolic waste products that accumulate during waking hours." },
    { id:"q3", type:"tf", q:"Sleep-deprived people are generally good at assessing their own impairment.", choices:["True","False"], correct:1, exp:"Sleep deprivation impairs one's ability to accurately assess one's own level of impairment." },
    { id:"q4", type:"mc", q:"Which brain region is most sensitive to sleep loss?", choices:["Cerebellum","Hippocampus","Amygdala","Prefrontal cortex"], correct:3, exp:"The prefrontal cortex — responsible for judgment and creativity — is disproportionately sensitive to sleep loss." },
  ],
  p11: [
    { id:"q1", type:"mc", q:"How many letters were in the shoebox?", choices:["12","27","43","51"], correct:2, exp:"There were forty-three letters in the shoebox." },
    { id:"q2", type:"tf", q:"The grandmother had posted the letters but never received replies.", choices:["True","False"], correct:1, exp:"None of the letters had ever been posted." },
    { id:"q3", type:"mc", q:"When was the most recent letter written?", choices:["August 1959","December 2019","January 2020","March 1946"], correct:1, exp:"The most recent letter was dated December 2019, three months before she died." },
    { id:"q4", type:"mc", q:"How did the translator react after reading the third letter?", choices:["She sent a written summary","She called to ask if the narrator was all right","She refused to continue","She wrote a note of admiration"], correct:1, exp:"The professor called after the third letter to ask if the narrator was all right." },
  ],
  p12: [
    { id:"q1", type:"mc", q:"What percentage of the ocean remains unexplored?", choices:["Over 40%","Over 60%","Over 80%","Over 95%"], correct:2, exp:"More than eighty percent of the ocean remains unmapped and unexplored." },
    { id:"q2", type:"tf", q:"We have more detailed maps of the seafloor than of the Moon.", choices:["True","False"], correct:1, exp:"We have more detailed maps of the lunar surface than of the seafloor." },
    { id:"q3", type:"mc", q:"What temperature gradient does the Pompeii worm tolerate?", choices:["20°C to 2°C","80°C to 2°C","60°C to 10°C","100°C to 5°C"], correct:1, exp:"The Pompeii worm tolerates temperatures exceeding 80°C at its tail while its head stays near 2°C." },
    { id:"q4", type:"mc", q:"How many human descents have reached the Challenger Deep?", choices:["One","Two","Three","Five"], correct:2, exp:"Only three descents by humans have ever reached the Challenger Deep, the most recent in 2019." },
  ],
};
